# Generated by Django 5.1.6 on 2025-04-06 14:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import interfaces.trainer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('credit_count', models.PositiveIntegerField(default=0, help_text='Renewal cycle count', verbose_name='Renewal Count')),
            ],
            options={
                'verbose_name': 'Trainer Payment History',
                'verbose_name_plural': 'Trainer Payment Histories',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.RemoveField(
            model_name='trainerattendance',
            name='trainer',
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['name'], 'verbose_name': 'Trainer', 'verbose_name_plural': 'Trainers'},
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='biometric_id',
        ),
        migrations.AddField(
            model_name='trainer',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Mark if trainer is blocked', verbose_name='Blocked Status'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Trainer Name'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary_credited_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Salary Credited Date'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary_due_date',
            field=models.DateTimeField(default=interfaces.trainer.models.get_default_salary_due_date, verbose_name='Salary Due Date'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['email'], name='trainer_tra_email_30db58_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['phone_number'], name='trainer_tra_phone_n_a1341c_idx'),
        ),
        migrations.AddField(
            model_name='trainerpaymenthistory',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='trainer.trainer', verbose_name='Trainer'),
        ),
        migrations.DeleteModel(
            name='TrainerAttendance',
        ),
        migrations.AddIndex(
            model_name='trainerpaymenthistory',
            index=models.Index(fields=['trainer'], name='trainer_tra_trainer_a7c2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerpaymenthistory',
            index=models.Index(fields=['transaction_date'], name='trainer_tra_transac_8fadcd_idx'),
        ),
    ]
