# Generated by Django 5.1.6 on 2025-04-09 09:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainerpaymenthistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerSalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_credited_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('salary_due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='trainer.trainer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TrainerPaymentHistory',
        ),
    ]
