# Generated by Django 5.1.6 on 2025-04-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_trainersalaryhistory_delete_trainerpaymenthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainersalaryhistory',
            old_name='Trainer',
            new_name='trainer',
        ),
    ]
