# Generated by Django 5.1.6 on 2025-03-12 15:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='employee ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='phone number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('role', models.CharField(choices=[('super_staff', 'Super Staff'), ('regular_staff', 'Regular Staff')], default='regular_staff', max_length=20, verbose_name='role')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='department')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salary')),
                ('salary_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='salary due')),
                ('salary_credited_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of the month salary is credited (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='salary credited day')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'staff member',
                'verbose_name_plural': 'staff members',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='staffuser_groups', to='auth.group', verbose_name='groups')),
                ('staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='staff.staffmember')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='staffuser_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'staff user',
                'verbose_name_plural': 'staff users',
            },
        ),
    ]
