# Generated by Django 5.1.6 on 2025-04-09 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('department', models.CharField(choices=[('front_desk', 'Front Desk'), ('cleaning', 'Cleaning Staff'), ('maintenance', 'Maintenance'), ('accounting', 'Accounting'), ('security', 'Security'), ('sales', 'Sales & Marketing'), ('customer_service', 'Customer Service')], db_index=True, max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_credited_date', models.DateField(default=django.utils.timezone.now)),
                ('salary_due_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='staff_photos/')),
                ('role', models.CharField(choices=[('regular_staff', 'Regular Staff'), ('super_staff', 'Super Staff')], db_index=True, default='regular_staff', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='staff_members', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='staff_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_credited_date', models.DateField(default=django.utils.timezone.now)),
                ('salary_due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
