# Generated by Django 5.1.6 on 2025-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='is_salary_paid',
            field=models.BooleanField(default=False, verbose_name='Salary Paid'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='last_salary_paid_on',
            field=models.DateField(blank=True, null=True, verbose_name='Last Salary Paid On'),
        ),
    ]
