# Generated by Django 5.1.6 on 2025-03-25 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name_snapshot', models.CharField(help_text='Name of the plan at the time of transaction', max_length=100)),
                ('plan_price_snapshot', models.DecimalField(decimal_places=2, help_text='Price of the plan at the time of transaction', max_digits=10)),
                ('plan_duration_snapshot', models.PositiveIntegerField(help_text='Duration (in days) of the plan at the time of transaction')),
                ('membership_start', models.DateTimeField(help_text='Membership start for this transaction')),
                ('membership_end', models.DateTimeField(help_text='Membership end for this transaction')),
                ('transaction_type', models.CharField(choices=[('initial', 'Initial Enrollment'), ('payment', 'Additional Payment'), ('renewal', 'Renewal'), ('plan_change', 'Plan Change')], default='payment', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Payment amount in this transaction', max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, help_text='Cumulative amount paid up to this transaction', max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, help_text='Remaining balance after this transaction', max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of the transaction')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='members.member')),
                ('membership_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membershipplan')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
