# Generated by Django 5.1.6 on 2025-02-26 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-attendance_date']},
        ),
        migrations.AddField(
            model_name='member',
            name='biometric_identifier',
            field=models.CharField(blank=True, help_text='Optional: store biometric hash/identifier if using biometric verification', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Mark if member is blocked'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_plan',
            field=models.ForeignKey(help_text='Assigned membership plan', on_delete=django.db.models.deletion.CASCADE, to='members.membershipplan'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_start',
            field=models.DateTimeField(help_text='Manually set by the manager'),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='Duration of the plan in days'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If locked, the plan cannot be modified once assigned.'),
        ),
    ]
