# Generated by Django 5.1.6 on 2025-02-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_attendance_options_member_biometric_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='biometric_identifier',
        ),
    ]
