# Generated by Django 5.1.6 on 2025-02-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_biometric_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount the member has paid so far', max_digits=10),
        ),
    ]
