# Generated by Django 5.1.6 on 2025-03-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_paymenthistory_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='plan_duration_snapshot',
            field=models.PositiveIntegerField(help_text='Plan duration (in days) at time of transaction'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='plan_name_snapshot',
            field=models.CharField(help_text='Plan name at time of transaction', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='plan_price_snapshot',
            field=models.DecimalField(decimal_places=2, help_text='Plan price at time of transaction', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of transaction'),
        ),
    ]
