# Generated by Django 5.1.6 on 2025-05-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_paymenthistory_plan_duration_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='biometric_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='biometric_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_end',
            field=models.DateTimeField(blank=True, help_text='Auto-calculated on save', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='If blocked, cannot assign to new members.'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='membership_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='membership_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='plan_duration_snapshot',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='plan_name_snapshot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='plan_price_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
